name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: fifsky/ssh-action@master
      with:
        command: |
          export GIT_SSH_COMMAND="ssh -i /root/.ssh/deploy_key -o IdentitiesOnly=yes"

          git config --global --add safe.directory /root/dominikbauer004_django
          cd /root/dominikbauer004_django

          git remote set-url origin git@github.com:${{ github.repository }}.git

          git reset --hard
          git clean -fd
          
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn.service
        host: ${{ secrets.SERVER_IP }}
        user: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
